// Chat persistence: load / save thread + messages, write per-turn telemetry.
// Anything that touches Postgres lives here so route handlers stay thin.

import { getDb, schema } from '@hamafx/db';
import type { Symbol } from '@hamafx/shared';
import type { ModelMessage, UIMessage } from 'ai';
import { asc, desc, eq } from 'drizzle-orm';

import { getMessageContent } from './utils/content';
import { estimateCostUsd } from './cost';

// ---------------------------------------------------------------------------
// Threads
// ---------------------------------------------------------------------------

export interface DbThread {
  id: string;
  title: string | null;
  /**
   * Provenance of `title`: `'llm'` = produced by `Title_Generator`,
   * `'fallback'` = deterministic local fallback, `null` = legacy row created
   * before the `title_source` column existed.
   */
  titleSource: 'llm' | 'fallback' | null;
  pinnedSymbol: Symbol | null;
  modelOverride: string | null;
  createdAt: number;
  updatedAt: number;
}

export async function listThreads(limit = 50): Promise<DbThread[]> {
  const rows = await getDb()
    .select()
    .from(schema.chatThreads)
    .orderBy(desc(schema.chatThreads.updatedAt))
    .limit(limit);
  return rows.map(rowToThread);
}

export async function getThread(id: string): Promise<DbThread | null> {
  const rows = await getDb()
    .select()
    .from(schema.chatThreads)
    .where(eq(schema.chatThreads.id, id))
    .limit(1);
  const row = rows[0];
  return row ? rowToThread(row) : null;
}

export async function createThread(opts: { pinnedSymbol?: Symbol | null } = {}): Promise<DbThread> {
  const inserted = await getDb()
    .insert(schema.chatThreads)
    .values({
      title: null,
      pinnedSymbol: opts.pinnedSymbol ?? null,
      modelOverride: null,
    })
    .returning();
  const row = inserted[0]!;
  return rowToThread(row);
}

/**
 * Persist a thread title together with its provenance.
 *
 * `source` is required so we can never accidentally drop the discriminator
 * that powers the auto-title telemetry/UX (`'llm'` = generated by
 * `Title_Generator`, `'fallback'` = deterministic local fallback). Both
 * columns are written in one UPDATE to keep them consistent.
 */
export async function updateThreadTitle(
  id: string,
  title: string,
  source: 'llm' | 'fallback',
): Promise<void> {
  await getDb()
    .update(schema.chatThreads)
    .set({ title, titleSource: source })
    .where(eq(schema.chatThreads.id, id));
}

export async function deleteThread(id: string): Promise<void> {
  await getDb().delete(schema.chatThreads).where(eq(schema.chatThreads.id, id));
}

export async function deleteAllThreads(): Promise<void> {
  await getDb().delete(schema.chatThreads);
}

function rowToThread(row: typeof schema.chatThreads.$inferSelect): DbThread {
  // `title_source` is a free-text column at the DB layer; narrow it here so
  // every consumer sees the canonical `'llm' | 'fallback' | null` union.
  const rawSource = row.titleSource;
  const titleSource: DbThread['titleSource'] =
    rawSource === 'llm' || rawSource === 'fallback' ? rawSource : null;
  return {
    id: row.id,
    title: row.title,
    titleSource,
    pinnedSymbol: row.pinnedSymbol as Symbol | null,
    modelOverride: row.modelOverride,
    createdAt: row.createdAt.getTime(),
    updatedAt: row.updatedAt.getTime(),
  };
}

// ---------------------------------------------------------------------------
// Messages
// ---------------------------------------------------------------------------

export interface DbMessage {
  id: string;
  threadId: string;
  role: 'user' | 'assistant' | 'system' | 'tool';
  content: string;
  /** Vercel AI SDK v5 message-parts JSON (tool calls, tool results, etc.). */
  parts: unknown;
  createdAt: number;
}

export async function listMessages(threadId: string, limit = 200): Promise<DbMessage[]> {
  const rows = await getDb()
    .select()
    .from(schema.chatMessages)
    .where(eq(schema.chatMessages.threadId, threadId))
    .orderBy(asc(schema.chatMessages.createdAt))
    .limit(limit);
  return rows.map((r) => ({
    id: r.id,
    threadId: r.threadId,
    role: r.role as DbMessage['role'],
    content: r.content,
    parts: r.parts,
    createdAt: r.createdAt.getTime(),
  }));
}

export async function appendUserMessage(threadId: string, message: UIMessage): Promise<void> {
  const text = extractText(message);
  // Phase 1 hardening §9 — a connection drop between the INSERT and the
  // sidebar-touching UPDATE used to leave the message persisted while
  // the thread's `updatedAt` stayed stale, which broke sidebar sort.
  // Wrap the pair in a transaction so either both writes land or both
  // roll back.
  await getDb().transaction(async (tx) => {
    await tx.insert(schema.chatMessages).values({
      threadId,
      role: 'user',
      content: text,
      parts: stripPartsForStorage(message.parts ?? null),
    });
    await tx
      .update(schema.chatThreads)
      .set({ updatedAt: new Date() })
      .where(eq(schema.chatThreads.id, threadId));
  });
}

export async function appendAssistantMessage(
  threadId: string,
  message: UIMessage,
): Promise<{ messageId: string }> {
  const text = extractText(message);
  // Phase 1 hardening §9 — same transactional pairing as the user-side
  // helper above. The sidebar sort cares about `updatedAt`, and the
  // telemetry caller relies on the returned `messageId` to attach
  // post-finish metrics.
  return getDb().transaction(async (tx) => {
    const inserted = await tx
      .insert(schema.chatMessages)
      .values({
        threadId,
        role: 'assistant',
        content: text,
        parts: stripPartsForStorage(message.parts ?? null),
      })
      .returning({ id: schema.chatMessages.id });
    await tx
      .update(schema.chatThreads)
      .set({ updatedAt: new Date() })
      .where(eq(schema.chatThreads.id, threadId));
    return { messageId: inserted[0]!.id };
  });
}

/**
 * Phase 3 hardening §21 — strip oversize fields before persisting the
 * `parts` JSONB. The model's `tool-result` parts can balloon when a
 * tool returns a base64 image (`analyze_chart_image` re-runs on the
 * user's attachment) or a long candle window. Trimming the obvious
 * offenders keeps the per-row size bounded so the chat sidebar
 * `SELECT *` query stays cheap and the JSON column doesn't grow into
 * the multi-MB range.
 *
 * Strategy: for each `tool-result` part, replace any field on
 * `output` whose name matches a known offender with `'[stripped]'`.
 * We don't try to recurse — the targets are flat keys today, and a
 * recursive walker would slow this hot path for marginal benefit.
 */
const STRIP_FIELDS: ReadonlySet<string> = new Set([
  // Base64 image payloads from analyze_chart_image / share_snapshot.
  'imageDataUrl',
  'image',
  'data',
  // Whole candle windows from analyze_technical / annotate_chart —
  // useful to the model in-flight, not useful in the persisted history.
  'candles',
  // Raw response bodies a tool may have buffered for debugging.
  'rawResponse',
]);

function stripPartsForStorage(parts: unknown): unknown {
  if (!Array.isArray(parts)) return parts;
  return parts.map((p) => {
    if (
      p === null ||
      typeof p !== 'object' ||
      !('type' in (p as Record<string, unknown>))
    ) {
      return p;
    }
    const part = p as { type: unknown; output?: unknown };
    if (part.type !== 'tool-result' || typeof part.output !== 'object' || part.output === null) {
      return p;
    }
    const output = part.output as Record<string, unknown>;
    let modified = false;
    const next: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(output)) {
      if (STRIP_FIELDS.has(k)) {
        next[k] = '[stripped]';
        modified = true;
        continue;
      }
      next[k] = v;
    }
    return modified ? { ...part, output: next } : p;
  });
}

/** Best-effort plain-text extraction from a UIMessage — used for search/title. */
function extractText(m: UIMessage): string {
  const parts = m.parts ?? [];
  const fromParts = parts
    .map((p) => {
      if (typeof p === 'object' && p !== null && 'type' in p) {
        if ((p as { type: string }).type === 'text') {
          return ((p as { text?: string }).text ?? '').trim();
        }
      }
      return '';
    })
    .filter(Boolean)
    .join('\n')
    .trim();
  
  if (fromParts) return fromParts;
  return getMessageContent(m as unknown as Record<string, unknown>).trim();
}

// ---------------------------------------------------------------------------
// Telemetry
// ---------------------------------------------------------------------------

export interface TelemetryInput {
  threadId: string;
  messageId: string | null;
  model: string;
  inputTokens: number;
  outputTokens: number;
  toolCalls: number;
  ms: number;
  /**
   * Row marker for non-assistant-turn telemetry. Legacy assistant-turn callers
   * omit this and the column stays `null`. Title_Generator emits one of:
   * `'title_generated' | 'title_failed' | 'title_skipped_budget'`. The Phase
   * 7a router emits `'routing_<domain>'`. The Phase 7c planner emits one of:
   * `'plan_generated' | 'plan_skipped_budget' | 'plan_failed'`.
   */
  kind?:
    | 'title_generated'
    | 'title_failed'
    | 'title_skipped_budget'
    | 'routing_fundamental'
    | 'routing_technical'
    | 'routing_summary'
    | 'routing_vision'
    | 'routing_generic'
    | 'plan_generated'
    | 'plan_skipped_budget'
    | 'plan_failed';
}

export async function recordTelemetry(t: TelemetryInput): Promise<void> {
  await getDb()
    .insert(schema.chatTelemetry)
    .values({
      threadId: t.threadId,
      messageId: t.messageId,
      model: t.model,
      inputTokens: t.inputTokens,
      outputTokens: t.outputTokens,
      toolCalls: t.toolCalls,
      ms: t.ms,
      estCostUsd: estimateCostUsd(t.model, t.inputTokens, t.outputTokens),
      kind: t.kind ?? null,
    });
}

// Re-export so route handlers don't need to import directly from `ai`.
export type { ModelMessage, UIMessage };


// ---------------------------------------------------------------------------
// Per-tool telemetry (Phase 7b)
// ---------------------------------------------------------------------------

export interface ToolTelemetryInput {
  threadId: string | null;
  messageId: string | null;
  tool: string;
  ms: number;
  ok: boolean;
  errorCode?: string | null;
}

export async function recordToolTelemetry(t: ToolTelemetryInput): Promise<void> {
  try {
    await getDb()
      .insert(schema.chatToolTelemetry)
      .values({
        threadId: t.threadId,
        messageId: t.messageId,
        tool: t.tool,
        ms: t.ms,
        ok: t.ok,
        errorCode: t.errorCode ?? null,
      });
  } catch (err) {
    // Tool-telemetry failures must never crash a chat turn.
    console.warn('[ai] tool telemetry insert failed', err);
  }
}
